default_language_version:
  python: python3.8


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
      - id: check-added-large-files
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Format imports

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
      - id: yapf
        args: [ --in-place, --parallel ]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.902'
#    hooks:
#      - id: mypy
