default_language_version:
  python: python3.8


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: [ --check, --diff ]

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
      - id: yapf
        args: [ --in-place, --parallel ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.902'
    hooks:
      - id: mypy
