<<<<<<< HEAD
[tool.isort]
profile = "black"
src_paths = ["pl_bolts", "tests"]
line_length = 120
=======
[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.autopep8]
max_line_length = 120
ignore = ["W504", "W504", "E402", "E731", "C40", "E741", "F40", "F841"]

[tool.black]
# https://github.com/psf/black
line-length = 120
target-version = ["py38"]
exclude = "(.eggs|.git|.hg|.mypy_cache|.nox|.tox|.venv|.svn|_build|buck-out|build|dist)"

[tool.isort]
known_first_party = [
    "benchmarks",
    "docs",
    "pl_examples",
    "pytorch_lightning",
    "tests",
]
skip_glob = [
    "pl_examples/*",
    "pytorch_lightning/accelerators/*",
    "pytorch_lightning/callbacks/*",
    "pytorch_lightning/cluster_environments/*",
    "pytorch_lightning/core/*",
    "pytorch_lightning/distributed/*",
    "pytorch_lightning/loggers/*",
    "pytorch_lightning/metrics/*",
    "pytorch_lightning/overrides/*",
    "pytorch_lightning/plugins/*",
    "pytorch_lightning/profiler/*",
    "pytorch_lightning/trainer/*",
    "pytorch_lightning/tuner/*",
    "pytorch_lightning/utilities/*",
    "tests/backends/*",
    "tests/base/*",
    "tests/callbacks/*",
    "tests/checkpointing/*",
    "tests/core/*",
    "tests/loggers/*",
    "tests/metrics/*",
    "tests/models/*",
    "tests/plugins/*",
    "tests/trainer/*",
    "tests/tuner/*",
    "tests/utilities/*",
]
profile = "black"
line_length = 120
force_sort_within_sections = "True"
order_by_type = "False"
>>>>>>> 90c1c0f68b4983c685e9d009482890e578800439
