[tool.isort]
known_first_party = [
    "pl_bolts",
    "tests",
    "docs",
    "notebooks",
]
profile = "black"
line_length = 120
order_by_type = "False"

[tool.black]
line-length = 120
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
