# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.0

references:

  install_deps: &install_deps
    run:
      name: Install Dependences
      command: |
        pip install -r requirements.txt --user
        sudo pip install pytest pytest-cov pytest-flake8
        pip install -r ./tests/requirements.txt --user

  tests: &tests
   run:
     name: Testing
     command: |
       python --version ; pip --version ; pip list
       coverage run --source pytorch_lightning_bolts -m py.test pytorch_lightning_bolts tests -v --doctest-modules --junitxml=test-reports/pytest_junit.xml
       coverage report
       codecov
     no_output_timeout: 30m

  install_pkg: &install_pkg
    run:
      name: Install package
      command: |
        virtualenv vEnv ; source vEnv/bin/activate
        pip install --editable . ; cd .. & python -c "import pytorch_lightning_bolts ; print(pytorch_lightning_bolts.__version__)"
        deactivate ; rm -rf vEnv

  create_pkg: &create_pkg
    run:
      name: Create package
      command: |
        #python setup.py check --metadata --strict
        sudo pip install twine==1.13.0
        python setup.py sdist
        twine check dist/*
        python setup.py clean

  format: &format
   run:
     name: Formatting
     command: |
       python --version ; pip --version ; pip list
       flake8

  make_docs: &make_docs
    run:
      name: Make Documentation
      command: |
        # sudo apt-get install pandoc
        pip install -r requirements.txt --user
        sudo pip install -r docs/requirements.txt
        # sphinx-apidoc -o ./docs/source ./pytorch_lightning **/test_* --force --follow-links
        cd docs; make clean ; make html --debug --jobs 2 SPHINXOPTS="-W"

jobs:

  Build-Docs:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - *make_docs
      - store_artifacts:
          # allows us to preview the generated html pages
          path: docs/build/html/
          destination: html

  Formatting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - *install_deps
      - *format

  Testing:
    docker:
      - image: circleci/python:3.7
    steps: &steps
      - checkout
      - *install_deps
      - *tests
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  Install-pkg:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - *create_pkg
      - *install_pkg


workflows:
  version: 2
  build:
    jobs:
      - Formatting
      - Testing
      - Build-Docs
      - Install-pkg
