name: Check Schema

on:
  push: {}
  pull_request:
    branches: [master, "release/*"]

jobs:
  validate-schema:
    uses: Lightning-AI/lightning/.github/workflows/_check-schema.yml@ci/decouple-schema.yml
