name: "Docs check"
# https://github.com/marketplace/actions/sphinx-build

on:  # Trigger the workflow on push or pull request, but only for the master branch
  push: {}
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  test-docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/base.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package & dependencies
        run: |
          pip install "pip==22.2.1"  # todo: drop after resolving extras
          pip install -e . -r requirements/devel.txt -r docs/requirements.txt \
            --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip list
        shell: bash

      - name: Test Documentation
        env:
          SPHINX_MOCK_REQUIREMENTS: 0
        run: |
          # First run the same pipeline as Read-The-Docs
          cd docs
          make doctest
          make coverage

  make-docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package
        run: pip install -e . --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        shell: bash

      - name: Install dependencies
        run: |
          # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
          sudo apt-get update && sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          pip install "pip==22.2.1"  # todo: drop after resolving extras
          pip install --requirement docs/requirements.txt
          pip list
        shell: bash

      - name: Make Documentation
        run: |
          # First run the same pipeline as Read-The-Docs
          cd docs
          make clean
          make html --debug --jobs 2 SPHINXOPTS="-W"

      - name: Upload built docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-results-${{ github.sha }}
          path: docs/build/html/
        # Use always() to always run this step to publish test results when there are test failures
        if: success()
