name: Greetings
# https://github.com/marketplace/actions/first-interaction

on: [issues]  # pull_request

jobs:
  greeting:
<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    runs-on: ubuntu-20.04
>>>>>>> 90c1c0f68b4983c685e9d009482890e578800439
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! thanks for your contribution!, great first issue!'
        pr-message: 'Hey thanks for the input! Please give us a bit of time to review it!'
